language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

install:
  - npm install

stages:
  - lint
  - name: gh_pages
    if: branch = master
  - name: github_release
    if: branch = master

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: gh_pages
      script: npm run build-example
      after_script:
        - cd ./example-dist
        - git init
        - git remote add origin "https://${GH_TOKEN}@${GH_REF}"
        - git checkout -b gh-pages
        - git config user.name "leezng"
        - git config user.email "im.leezng@gmail.com"
        - git add .
        - git commit -m "update example page"
        - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
    - stage: github_release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: ${GH_TOKEN}
        skip_cleanup: true
        on:
          tags: true

env:
  global:
    - GH_REF: github.com/leezng/vue-text-editor.git
